api_key: null
cookie:
  expiry_days: 7
  key: gH7k9P2oV4hQeZ1rBn6LsXa9Jf3tW
  name: hugging_face_topo_art_ui
credentials:
  usernames:
    ann:
      failed_login_attempts: 0
      logged_in: false
      password: $2b$12$UlxhIVP1j2JvF5LLYz5AJue/hvrKOHK7fco1MB4XaByX2Du4oKIRK
    dmcnay:
      failed_login_attempts: 0
      logged_in: false
      password: $2b$12$JHTO7BMKVpgsoL3Pvtk9y.gJlCUPpghGGteXZbg734a0TFl8aO6ye
    placeswekeep:
      failed_login_attempts: 0
      logged_in: false
      password: $2b$12$fxtkh2yRVoJDbYFKZz2dIuXNJKT3.EcpdpxOfXVfasrB8Lv1yqCYe
    splodgie:
      failed_login_attempts: 0
      logged_in: false
      password: $2b$12$EDfsdGQWFfYyn5Miyzju.u8SqGuWfVNu0Zo./1M7qX.XgpEiR9TXS
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - dmcnay3@gatech.edu
  - djmcnay@gmail.com
