[theme]
primaryColor            = "#2F0A61"         # Surrey Blue
textColor               = "#333333"
#backgroundColor         = "#FFFFFF"         # Surrey Gold
#secondaryBackgroundColor= "#F6F6F6"
#font                    = "sans serif"